{{- if and .Values.enabled (not .Values.app.translation.existingSecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cacheppuccino.fullname" . }}
  labels:
    {{- include "cacheppuccino.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRANSLATION_API_KEY: {{ .Values.app.translation.apiKey | quote }}
{{- end }}
