enabled: true
replicaCount: 1

image:
  repository: ghcr.io/ifrcgo/cacheppuccino
  tag: 'SET-BY-CICD-TAG'
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

# NOTE:
# cacheppuccino currently runs as root in Docker for SQLite volume simplicity.
# Keep this as-is if you use SQLite PVC.
securityContext:
  runAsUser: 0
  runAsGroup: 0
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  tls:
    enabled: false
    secretName: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

app:
  listenAddr: ":8080"
  logLevel: info

  translation:
    baseUrl: ""
    applicationId: ""
    # if provided, chart will create a Secret (unless existingSecret is set)
    apiKey: ""

    # prefer using an existing Secret (e.g., ExternalSecrets)
    existingSecret:
      name: ""
      key: "TRANSLATION_API_KEY"

  pull:
    interval: "10m"
    httpTimeout: "30s"
    initialPullDeadline: "45s"

sqlite:
  enabled: true
  mountPath: /data
  filename: cacheppuccino.db

  # If set, chart will not create PVC and will use existingClaim
  existingClaim: ""

  pvc:
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 500Mi

# Azure Key Vault CSI Driver
secretsStoreCsiDriver:
  create: false
  provider: azure

  # optional overrides
  secretProviderClassName: ""
  secretName: ""

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ""
    keyvaultName: ""
    tenantId: ""
  secretsKeyMap: {}
    # TRANSLATION_API_KEY: "TRANSLATION-API-KEY"
